name: tts3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - TTS>=0.22.0
      - torch>=2.0.0
      - torchaudio>=2.0.0
      - numpy>=1.21.0
      - scipy>=1.7.0
      - librosa>=0.9.0
      - soundfile>=0.12.0
      - matplotlib>=3.5.0
      - tqdm>=4.64.0
      - requests>=2.28.0
